version: '2.1'
services:
  mysqldb:
    image: mysql:5
    mem_limit: 1073741824
    restart: unless-stopped
    ports:
      - "3308:3306/tcp"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: scala
